import { test, expect } from '@playwright/test';
test('registration follows the required fields and centers its title', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'เริ่มต้นใช้งาน', exact: true }).click();
  await page.getByRole('button', { name: 'ยังไม่มีบัญชี · สมัครสมาชิก' }).click();
  const heading = page.getByRole('heading', { name: 'สร้างบัญชีผู้ใช้' });
  await expect(heading).toBeVisible();
  await expect(page.getByText('เริ่มดูแลเจ้าเหมียวอย่างใกล้ชิด')).toHaveCount(0);
  await expect(page.getByLabel('โทรศัพท์ (ไม่บังคับ)')).toHaveCount(0);
  for (const label of ['ชื่อ', 'นามสกุล', 'อีเมล', 'ชื่อผู้ใช้', 'รหัสผ่าน']) await expect(page.getByLabel(label, { exact: true })).toBeVisible();
  const box = await heading.boundingBox();
  expect(box).not.toBeNull();
  expect(Math.abs(box!.x + box!.width / 2 - 393 / 2)).toBeLessThan(3);
  await page.getByRole('button', { name: 'สมัครสมาชิก', exact: true }).click();
  await expect(page.getByText('กรุณากรอกชื่อและนามสกุล')).toBeVisible();
});
test('profile menu opens settings and signs out of demo', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'ทดลองใช้ด้วยข้อมูลสาธิต' }).click();
  await expect(page.getByLabel('รูปโปรไฟล์ของฉัน')).toBeVisible();
  await page.getByRole('button', { name: 'เปิดบัญชีของฉัน' }).click();
  await expect(page.getByRole('button', { name: 'ตั้งค่า', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'ตั้งค่า', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'โปรไฟล์และการตั้งค่า' })).toBeVisible();
  await page.getByRole('button', { name: 'เปิดบัญชีของฉัน' }).click();
  await page.getByRole('button', { name: 'ออกจากโหมดสาธิต', exact: true }).first().click();
  await expect(page.getByRole('button', { name: 'เริ่มต้นใช้งาน', exact: true })).toBeVisible();
});
test('guest searches Thai guides and private records require login', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'เริ่มต้นใช้งาน', exact: true })).toBeVisible();
  await page.screenshot({ path: '../artifacts/welcome.png' });
  await page.getByRole('button', { name: 'อ่านคู่มือโดยไม่เข้าสู่ระบบ' }).click();
  await page.getByLabel('ค้นหาคู่มือ', { exact: true }).fill('หางตั้ง');
  await page.getByRole('button', { name: 'หางตั้งขึ้น ปลายงอเล็กน้อย', exact: true }).click();
  await expect(page.getByText('ท่าทางนี้บอกอะไรเรา')).toBeVisible();
  await page.getByRole('tab', { name: 'ประวัติ', exact: true }).click();
  await expect(page.getByRole('button', { name: 'เข้าสู่ระบบ / สมัครสมาชิก' })).toBeVisible();
  expect(errors).toEqual([]);
});
test('demo persists log CRUD and manages cats, vaccinations and profile', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto('/');
  await page.getByRole('button', { name: 'ทดลองใช้ด้วยข้อมูลสาธิต' }).click();
  await expect(page.getByText('วันนี้ของมะลิ', { exact: true })).toBeVisible();
  await page.screenshot({ path: '../artifacts/dashboard.png' });
  await page.getByRole('tab', { name: 'คู่มือ', exact: true }).click();
  await page.screenshot({ path: '../artifacts/guides.png' });
  await page.getByRole('tab', { name: 'บันทึก', exact: true }).click();
  await page.getByRole('button', { name: 'บันทึกข้อมูล', exact: true }).click();
  await expect(page.getByText('กรุณากรอกพฤติกรรม', { exact: true })).toBeVisible();
  await page.getByLabel('พฤติกรรม / หัวข้อบันทึก', { exact: true }).fill('ทดสอบแมวเดินเล่น');
  await page.getByLabel('หมายเหตุเพิ่มเติม', { exact: true }).fill('ทดสอบบันทึกจากหน้าจอจริง');
  await page.getByRole('button', { name: 'บันทึกข้อมูล', exact: true }).click();
  await page.getByRole('tab', { name: 'ประวัติ', exact: true }).click();
  await page.getByLabel('ค้นหาบันทึก', { exact: true }).fill('ทดสอบแมวเดินเล่น');
  await page.getByRole('button', { name: 'ทดสอบแมวเดินเล่น', exact: true }).click();
  await page.getByLabel('หมายเหตุเพิ่มเติม', { exact: true }).fill('แก้ไขแล้ว');
  await page.getByRole('button', { name: 'บันทึกการแก้ไข' }).click();
  await expect(page.getByText('บันทึกเรียบร้อยแล้ว', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'ทดลองใช้ด้วยข้อมูลสาธิต' }).click();
  await page.getByRole('tab', { name: 'ประวัติ', exact: true }).click();
  await page.getByRole('button', { name: 'ทดสอบแมวเดินเล่น', exact: true }).click();
  await expect(page.getByLabel('หมายเหตุเพิ่มเติม', { exact: true })).toHaveValue('แก้ไขแล้ว');
  await page.getByRole('button', { name: 'ลบบันทึกนี้', exact: true }).click();
  await page.getByRole('button', { name: 'ยืนยันลบบันทึก', exact: true }).click();
  await expect(page.getByText('ลบบันทึกแล้ว', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'ทดสอบแมวเดินเล่น', exact: true })).toHaveCount(0);
  await page.getByRole('tab', { name: 'บัญชี', exact: true }).click();
  await page.getByRole('button', { name: 'แมวและบ้านของเรา', exact: true }).click();
  await page.getByRole('button', { name: 'เพิ่มโปรไฟล์แมว', exact: true }).click();
  await page.getByLabel('ชื่อแมว', { exact: true }).fill('ส้มทดสอบ');
  await page.getByRole('button', { name: 'สายพันธุ์', exact: true }).click();
  await page.getByRole('button', { name: 'เลือกสายพันธุ์ แมวไทย' }).click();
  await expect(page.getByText('หมายเลขไมโครชิป')).toHaveCount(0);
  await page.getByRole('button', { name: 'วันเกิด', exact: true }).click();
  await expect(page.getByRole('button', { name: 'เลือกปี' })).toBeVisible();
  await page.getByRole('button', { name: 'เลือกวันที่ 1', exact: true }).click();
  await page.getByRole('button', { name: 'บันทึกโปรไฟล์แมว' }).click();
  await expect(page.getByRole('button', { name: 'แก้ไข ส้มทดสอบ', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'บัญชี', exact: true }).click();
  await page.getByRole('button', { name: 'วัคซีนและการแจ้งเตือน' }).click();
  await page.getByRole('button', { name: 'เพิ่มวัคซีน / นัดหมาย', exact: true }).click();
  await page.getByLabel('ชื่อวัคซีนหรือนัดหมาย', { exact: true }).fill('นัดตรวจทดสอบ');
  await page.getByRole('button', { name: 'บันทึกวัคซีน / นัดหมาย', exact: true }).click();
  await expect(page.getByRole('button', { name: 'แก้ไข นัดตรวจทดสอบ', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'บัญชี', exact: true }).click();
  await page.getByRole('button', { name: 'แก้ไขโปรไฟล์', exact: true }).click();
  await page.getByLabel('ชื่อและนามสกุล', { exact: true }).fill('ผู้ทดสอบ แอปแมว');
  await page.getByRole('button', { name: 'บันทึกโปรไฟล์', exact: true }).click();
  await expect(page.getByText('ผู้ทดสอบ แอปแมว', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
